name: Build macOS Version
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Nativefier
        run: sudo npm install -g nativefier

      - name: Build macOS
        run: |
          nativefier --name "EndlessCityRacer" \
          --platform "mac" \
          --arch "x64" \
          --browserwindow-options '{ "webPreferences": { "nodeIntegration": false } }' \
          "index.html"

      - name: Check Folder
        run: ls -R

      - name: Upload macOS Build
        uses: actions/upload-artifact@v4
        with:
          name: EndlessCityRacer-macOS
          path: EndlessCityRacer-darwin-x64/
