name: Build EXE
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Nativefier
        run: npm install -g nativefier

      - name: Create EXE
        run: |
          nativefier --name "EndlessCityRacer" --platform "windows" --arch "x64" "file://${{ github.workspace }}/index.html" --internal-urls ".*"

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: EndlessCityRacer-Windows
          path: ./*-win32-x64/
